name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Ou qualquer branch que você deseja usar para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Versão do .NET que você está usando

      - name: Install dependencies
        run: dotnet restore ./publish/Beanstalk.csproj

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application-name: app-netcore  # Nome da aplicação no Elastic Beanstalk
          environment-name: app-core-dev  # Nome do ambiente no Elastic Beanstalk
          version-label: ${{ github.sha }}  # Usando o SHA do commit como rótulo de versão
          region: us-east-1  # Região da AWS onde seu Elastic Beanstalk está configurado
          deployment-package: ./publish

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



